import { Roboto_Serif } from "next/font/google";
import "./globals.css";
import NavItems from "@/app/Components/Navbar/NavItems";
import FooterBar from "@/app/Components/Footer/FooterBar";
import { ReduxProvider } from "@/redux/Provider/ReduxProvider";


const robotoSerif = Roboto_Serif({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
      <body className={robotoSerif.className}>
        
        <NavItems />
        <main>
        {children}
        </main>
        <FooterBar />
        </body>
        </ReduxProvider>
    </html>
  );
}
